### ISSUE TITLE
TensorBoard Empty

### ISSUE THREAD

**Issue by JohnRobson** [hpssjellis/tensorflow-udacity-deep-learning#2]
In my TensorBoard I got:

No scalar summary tags were found
No image tags were found
No graph definition files were found
No histogram tags were found.

What should I do?

Thank you.

**Comment by hpssjellis** [comment]
Did you get the very basic graph, like the one below. Events, images and histogram are not shown on mine but the graph should work

![image](https://cloud.githubusercontent.com/assets/5605614/15095499/c5bfd404-147d-11e6-8839-5ed1871eca58.png)

**Comment by hpssjellis** [comment]
I think you have to run the example before the tensorboard example since it downloads the files needed.

**Comment by JohnRobson** [comment]
You are right, now is OK, thank you.

**Comment by hpssjellis** [comment]
Great. Have a good day.

P.S. I get these things going but have not had much time to learn much about Tensorflow. If you find any great examples or websites, please let me know.
